# Generated by Django 5.1.4 on 2024-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baptism", "0008_alter_fieldtable_choice_alter_fieldtable_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baptism",
            name="advanced_baptism_id",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="baptism",
            name="child_name_second",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
