# Generated by Django 5.1.4 on 2024-12-14 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baptism", "0009_alter_baptism_advanced_baptism_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="logindetails",
            old_name="user_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="logindetails",
            name="password",
        ),
        migrations.RemoveField(
            model_name="logindetails",
            name="user_name",
        ),
        migrations.AddField(
            model_name="logindetails",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
