# Generated by Django 5.1.4 on 2024-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baptism", "0011_alter_logindetails_id_alter_logindetails_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baptism",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
